---
- name: Create hadoop group
  group:
    name: "{{hadoop_group}}"
    system: yes

- name: Create hadoop user
  user:
    name: "{{hadoop_user}}"
    group: "{{hadoop_group}}"
    system: yes

- name: Create .ssh folder
  file:
    path: "/home/{{hadoop_user}}/.ssh"
    state: directory
    mode: 0700
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"

- name: Copy ssh key
  copy:
    src: "{{item}}"
    dest: "/home/{{hadoop_user}}/.ssh"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
    mode: 0600
  with_items:
    - "{{ hadoop_ssh_private_key }}"
    - "{{ hadoop_ssh_authorized_keys }}"

# Pakages for RedHat family OS
- name: Yum install prerequisites
  yum: pkg={{ item }} state=installed
  environment: "{{proxy_env}}"
  when: ansible_os_family == 'RedHat'
  with_items:
    - wget
    - gzip
    - tar
    - java-1.7.0-openjdk

# Pakages for Debian family OS
- name: Apt install prerequisites
  apt: pkg={{ item }} state=installed update_cache=yes
  environment: "{{proxy_env}}"
  when: ansible_os_family == 'Debian'
  with_items:
    - wget
    - gzip
    - tar
    - default-jre-headless
